### ISSUE TITLE
Minify CSS and combine JS as part of collectstatic and build

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#100]
From #88.

**Comment by aboutaaron** [comment]
https://django-compressor.readthedocs.io/en/latest/

**Comment by aboutaaron** [comment]
I'd also look into doing offline compression since we serve a static version of the site: https://django-compressor.readthedocs.io/en/latest/usage/#offline-compression

**Comment by sahilchinoy** [comment]
So the way it's done [here](https://github.com/cirlabs/django-project-template/blob/master/project_name/settings/production.py#L13) is to turn on `COMPRESS_OFFLINE` in production and then hook up the compression management command into a fabric task. We currently don't have two separate settings files, so I don't think this solution will work for us. Ideas?

**Comment by palewire** [comment]
We can probably add it as a .env variable or maybe an if statement in the
setting keyed off our PRODUCTION variable.

**Comment by sahilchinoy** [comment]
The simplest solution ended up being forcing django-compressor's `compress` command to run as part of our deploy routine. So `COMPRESS_OFFLINE` is always technically `FALSE`, but when we build the site, the static CSS and JS should still get be created before we deploy. There could easily be something wrong with this, so let's monitor.

**Comment by palewire** [comment]
How can we test it? Roll out the site with the new code?

**Comment by sahilchinoy** [comment]
Yeah so this doesn't work. I realized that it's not that we want to turn on `COMPRESS_OFFLINE` only for prod, but rather we want it on when we're running the build/deploy routine (dev & prod) as opposed to the local runserver. Struggling with how to accomplish that.

**Comment by palewire** [comment]
Here. Let me. 

![](https://media.giphy.com/media/akM24JppWNGeY/giphy.gif)

**Comment by palewire** [comment]
it me irl rn 

![](http://mlb.mlb.com/images/4/2/2/139162422/072715_chc_bryant_walkoff_hr_med_1_3rdonmvg.gif)
