### ISSUE TITLE
font-weight: 300 doesn't look awesome on some older machines

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#101]
Like mine!

![screenshot - 08202016 - 05 13 55 pm](https://cloud.githubusercontent.com/assets/9993/17834536/92483a34-66f9-11e6-8bef-e6120aabd1a4.png)

From #88.

**Comment by aboutaaron** [comment]
Using the correct font style should solve this (in lieu of changing the font weight)

**Comment by gordonje** [comment]
Screencap from Safari on my iPhone 5s. Looks like the font-family isn't loading? But looks fine on Chrome on my desktop.

![image](https://cloud.githubusercontent.com/assets/4304548/18138758/e351401a-6f73-11e6-9f8c-1dd67779b842.png)

**Comment by gordonje** [comment]
Same on mobile Chrome browser. 

![image](https://cloud.githubusercontent.com/assets/4304548/18139221/10fe820a-6f76-11e6-9ee8-4fb86a4868b0.png)

**Comment by palewire** [comment]
If iOS is against us we have a problem.

**Comment by aboutaaron** [comment]
I'm curious how the fonts are loaded. We can try to debug

**Comment by palewire** [comment]
Alrighty. Please try again. Big refactor just pushed.

I downloaded Source Sans Pro directly from Adobe's github account. Those files are now hosted in our static directory rather than being pulled in from the Google CDN. Then I subbed in Adobe's recommended CSS font-face. It's working pretty well on my old Xubuntu machine, but you guys will have to tell me about other platforms

**Comment by gordonje** [comment]
Looks 👌 on Safari and Chrome in my phone.

**Comment by palewire** [comment]
Excellent.
