### ISSUE TITLE
clicking on `wget` or `curl` should show appropriate code to download data

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-downloads-website#103]
We have an example for `curl` but not `wget`. Maybe we should make it so tapping on the commands should switch the script displayed. This could be nice in case someone is using `wget` but doesn't remember how to return the output

**Comment by sahilchinoy** [comment]
Was the consensus on this to kill `wget`?

**Comment by palewire** [comment]
KILL IT DEAD
