### ISSUE TITLE
Another pass at how we're disclosing errors that treats them as footnotes

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#104]
- [x] Astericks on full archive robograf linking to bottom foonote
- [x] Askericks on each record count for tables with errors
- [x] Remove error count from table boxes
- [x] New footnote/errata section at the bottom that:
  - [x] Explain the phenomonen of missing records
  - [x] Report the percentage of records missing
  - [x] Report that errors logs are included in the big ZIP download
  - [x] List and link to the error logs for each table that is missing records

**Comment by sahilchinoy** [comment]
I took a stab at this, but don't love keeping all the files in a list. Could reformat into a table, but that's starting to take up a lot of space for what are supposed to be footnotes... Thoughts?

**Comment by palewire** [comment]
Great job. I made a few small changes and switched the headline to the more specific "Errata."
