### ISSUE TITLE
Forms section on file detail is a little toothy and bland

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#109]
Can we spiff up the styles on this a little?

![screenshot - 08292016 - 07 52 00 pm](https://cloud.githubusercontent.com/assets/9993/18074550/4588eed4-6e22-11e6-9a37-4e854a8aa3a2.png)

**Comment by sahilchinoy** [comment]
I made some changes here, looks more like our fields section now. Still, admittedly, bland.

**Comment by palewire** [comment]
Still a big improvement. And gives us some consistency between sections. Good job.
