### ISSUE TITLE
Sample gists for empty files

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-downloads-website#116]
The details pages for the empty files (e.g., [`CVR_F470_CD`](http://calaccess.californiacivicdata.org/files/cvr-f470-cd/)) oddly include gists of sample data. Turns out this is sample data from other files, likely the result of a bug in the `updatesamplefilegists` command.

**Comment by gordonje** [comment]
@palewire and @sahilchinoy: This last commit was my attempt to deal cases when there actually isn't a sample file by hiding that section from the file details page, rather than have "Sample: A few sample rows." Quite possible there's a better way, tho...

**Comment by palewire** [comment]
Seems fine to me.
