### ISSUE TITLE
A bug on both the homepage and version detail page promoting the processed files that are TK

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#117]

**Comment by sahilchinoy** [comment]
I quickly tried putting this above the affix-nav (a la GitHub), but didn't love it. I'm thinking it might work better as a separate section. Thoughts?

![screen shot 2016-09-13 at 5 32 07 pm](https://cloud.githubusercontent.com/assets/1947356/18496110/1a553c74-79d8-11e6-8949-2fdbbc777741.png)

**Comment by palewire** [comment]
Yeah. I see what you mean. It's pretty narrow at the width we currently have it.

**Comment by palewire** [comment]
Looks like github pulls it off by going wider and using tiny type. 

![screenshot from 2016-09-13 17-43-21](https://cloud.githubusercontent.com/assets/9993/18496308/bd1bf686-79d9-11e6-97a7-68294d223f5c.png)

**Comment by sahilchinoy** [comment]
Here's the promotion text I'm working with: "We're working on processed files that shape our cleaned-up data into meaningful models that are even easier to use."

**Comment by palewire** [comment]
That's about it, though I wonder if we can use less technical language -- and then link to our launch blog post.

"COMING SOON:  Easy-to-analyze flat files of the most valuable data"
