### ISSUE TITLE
Build the new hero element

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#130]
Designed in #66 with the "geo bear" topper

**Comment by aboutaaron** [comment]
Right now, the hero is sitting in the container, but I think we'll get a cleaner effect if the hero lives outside the container. Ideally, the bear, would emerge from the left side of browser window, rather than out of the container div, since that leaves whitespace to the right of the logo

**Comment by aboutaaron** [comment]
Thoughts on a hero approach like this? I have the implementation more or less done locally. We'd need to re-adjust for mobile, but I think this adds some much _punch_ to the page. I also added a new font, Raleway, to break up Source Sans Pro's takeover. Lemme know what y'all think. I can probably push something close to this later tonight.

![fireshot capture 1 - california civic data coalition - http___127 0 0 1_8000_](https://cloud.githubusercontent.com/assets/856628/18413474/db363dd0-7776-11e6-894b-30cc160feaf2.png)

**Comment by palewire** [comment]
I like it broadly but I'm wondering if the zone where the new red
background and the brown bear overlaps needs a little finesse yet.

**Comment by aboutaaron** [comment]
We could try something more subtle ... I think the bear flying solo isn't enough, so something needs to be added. I can also adjust the colors on the bear and see if we can come up with something tighter for the homepage

![screen shot 2016-09-10 at 5 03 28 pm](https://cloud.githubusercontent.com/assets/856628/18413531/8c189fac-7778-11e6-8e27-05d82b26d647.png)

**Comment by palewire** [comment]
Maybe that's it. I trust you so give it a run.

**Comment by palewire** [comment]
Alrighty. I've finished a first pass. @aboutaaron feel free to overwrite any of my heresies.
