### ISSUE TITLE
geobear might need modification for the red backround of the footer

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#132]
I just slammed in our geobear logo into our footer and here's how it looks. 

![screenshot - 09052016 - 02 56 11 pm](https://cloud.githubusercontent.com/assets/9993/18257475/f936d774-7378-11e6-8102-21d2db26a8b2.png)

The red star obviously doesn't read on the red background. We should do something here.

Things I can imagine:
- Crop out the star and let the brown bear ride alone, as is
- Reverse out the logo into white on a transparent or red background so it matches the header lettering color, with or without the star

Any other ideas?

For #66.

**Comment by palewire** [comment]
Here's what a really quick and hacky reversed out version looks like.

![screenshot - 09052016 - 03 02 35 pm](https://cloud.githubusercontent.com/assets/9993/18257516/d492e0ba-7379-11e6-9ea0-959e6c4f316d.png)

**Comment by palewire** [comment]
Here's what a quick and dirty take on how just the brown bear looks.

![screenshot - 09052016 - 03 04 38 pm](https://cloud.githubusercontent.com/assets/9993/18257526/1d834332-737a-11e6-909f-4ebe9e044c94.png)

**Comment by aboutaaron** [comment]
I dig the white!

**Comment by palewire** [comment]
Okay. Let's do it. If you drop an SVG or vector version in #66 we can probably start jamming it all over the place.

**Comment by aboutaaron** [comment]
New image attached in #66
