### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#144]
Who wants to have fun?

**Comment by aboutaaron** [comment]
Ideas:
- California sinking off the continent
- Exploding/shattering geobear
- geobear => real bear

**Comment by gordonje** [comment]
@yarynam @NathanLawrence Wanna help? Could use some of your SVG animation skills.

**Comment by yarynam** [comment]
@gordonje  Would like to =)

**Comment by palewire** [comment]
There's a free t-shirt in it for you!
