### ISSUE TITLE
What do we do with geobear on mobile?

### ISSUE THREAD

**Issue by sahilchinoy** [california-civic-data-coalition/django-calaccess-downloads-website#147]
This looks a little weird, but I don't want to kill it entirely.

![screen shot 2016-09-12 at 11 57 24 pm](https://cloud.githubusercontent.com/assets/1947356/18464244/acacfa10-7944-11e6-9f9f-86b2c786fdcd.png)

**Comment by palewire** [comment]
For consistency, one thing we could do is put a full gray background, sort of like sliced triangle of desktop, over the entire header. That might give that top a little more shape, though the bear is still a little rando. 

As a standalone element on this view, perhaps it could be paired with a line declaring this a product of the CCDC or something.

@aboutaaron you have any thoughts?

**Comment by palewire** [comment]
This is now the iPhone 6 size in my desktop Chrome emulator. Better? Worse?

![screenshot from 2016-09-13 11-12-47](https://cloud.githubusercontent.com/assets/9993/18485769/0bc87b92-79a3-11e6-8086-f3e72c385d4d.png)

**Comment by palewire** [comment]
I'm going to close this ticket since this is the best solution I can come up with. If anybody has an alternative to offer, I would welcome it.
