### ISSUE TITLE
Is it real bad to cut the filesize and error count on mobile?

### ISSUE THREAD

**Issue by sahilchinoy** [california-civic-data-coalition/django-calaccess-downloads-website#149]
Responsive tables are hard. Short of reflowing the entire thing, this is the only way I can think to avoid horizontal scrolling at the smallest screen sizes.

![screen shot 2016-09-13 at 12 27 01 am](https://cloud.githubusercontent.com/assets/1947356/18464962/e9f7330a-7948-11e6-8c56-751cf0b00612.png)

**Comment by palewire** [comment]
Probably not a big deal to cut them. Though I wonder if trying [Bootstrap's responsive tables](http://getbootstrap.com/css/#tables-responsive) would be any better.
