### ISSUE TITLE
Outline for launch blog post

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#151]
Here's a rough outline for a blog post announcing our site launch.
- Introduce new website, an archive of the CAL-ACCESS data dump with cleaned up files and documentation.
- List the features
  - New website that updates daily and archives every snapshot
    - Screenshot of the homepage
  - Cleaned up raw files
  - Served together in bulk as a ZIP
  - But also as individual CSVs
    - Screenshot of the latest download page
  - Stable "latest" URLs amount to an API at calaccess.download
    - code sample of a curl request piping ZIP file into an unzip
    - code sample of a curl request piping a CSV file into csvkit or your database or something
  - Linked up documentation for files
    - Screenshot of a file detail page
  - ONA shoutout
  - Also for forms
    - Screenshot of a form detail page
- What's to come
  - Easier to use processed files that simplify the crazy CAL-ACCESS structure.
    - Point over to the processed-data repo
  - This release is really more for the hardcore. But newbies just wait, there's more coming.
- T-shirt contest
  - Hype the new logo
  - Show it on a t-shirt
  - Tell people that the first 5 to file a bug report will get a free shirt
  - Show where people can file issues on GitHub
  - Can you make us a 404 page?
- Peace out

Others, feel free to edit this with your own ideas

**Comment by palewire** [comment]
Here are a couple t-shirt designs. @aboutaaron, @gordonje, @sahilchinoy: You have any favorites?

![screenshot from 2016-09-14 13-24-26](https://cloud.githubusercontent.com/assets/9993/18529389/bb164b90-7a81-11e6-8935-9434105f86b9.png)

![screenshot from 2016-09-14 13-18-25](https://cloud.githubusercontent.com/assets/9993/18529388/bb135714-7a81-11e6-87c8-da2b6d77db53.png)

![screenshot from 2016-09-14 13-17-02](https://cloud.githubusercontent.com/assets/9993/18529390/bb165428-7a81-11e6-8b23-3567bb81323d.png)

**Comment by palewire** [comment]
![screenshot from 2016-09-14 13-56-02](https://cloud.githubusercontent.com/assets/9993/18529705/194374a8-7a83-11e6-876c-e00f3593ce6e.png)

**Comment by gordonje** [comment]
Ooooo tight. I kinda like option 1 the most.

**Comment by palewire** [comment]
Option 1 seems to be the crowd favorite as I show this to people.

**Comment by gordonje** [comment]
I like the differing shades of brown, whatever background that works on. I actually don't hate it on red. Not really into the extra border necessary in option 4.

**Comment by palewire** [comment]
After we launch this post, we need to remember to update the "Learn more" link on the homepage to go to it.

**Comment by gordonje** [comment]
Got a [draft](https://github.com/california-civic-data-coalition/california-civic-data-coalition.github.io/blob/master/_posts/2016-09-15-website-launch.markdown) going. Need to add in screen-caps and links still. Let me know what sucks.
