### ISSUE TITLE
Download buttons under Archived files bleeding over border

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-downloads-website#152]
On version details
![download_btns](https://cloud.githubusercontent.com/assets/4304548/18514865/d5beaa7e-7a58-11e6-8029-550e78debf0b.png)

**Comment by palewire** [comment]
[![](https://media.giphy.com/media/Q4duvHQAFZ9de/giphy.gif)](https://www.youtube.com/watch?v=J5K2qkakn40)

**Comment by palewire** [comment]
![](https://media.giphy.com/media/Q4duvHQAFZ9de/giphy.gif)
