### ISSUE TITLE
GET request when user hits ENTER on Filter files search field on version_details

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-downloads-website#153]
The files search field returns results as the user is typing, which is fast and awesome.

But if the user does hit ENTER (as I did), the form makes a GET request that causes the page to reload with a `?` at the end of the url, like `http://calaccess.californiacivicdata.org/downloads/latest/?`

Maybe we should just disable the ENTER key?

**Comment by palewire** [comment]
Good catch
