### ISSUE TITLE
A little love to landscape mobile sizing

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#156]

**Comment by sahilchinoy** [comment]
You mean this won't work?

![localhost-8000- iphone 5 1](https://cloud.githubusercontent.com/assets/1947356/18523324/aaeb7376-7a68-11e6-9ee6-8bc5eea82aa0.png)

**Comment by palewire** [comment]
My Android Nexus 5 is actually pretty okay when I look at it. What bugs are you guys seeing?

**Comment by sahilchinoy** [comment]
On my iPhone 5 emulator, geobear takes up the full width and height of the screen on the homepage. Not the end of the world, but perhaps we just make it smaller? Does this work?

![localhost-8000- iphone 5 2](https://cloud.githubusercontent.com/assets/1947356/18523671/0e06394a-7a6a-11e6-8a7a-3ba0d7d012ef.png)

**Comment by palewire** [comment]
It doesn't bother me too much, but if it bugs you guys and it's an easy fix that doesn't affect our other views I'm fine with the change.
