### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-downloads-website#158]
I imagine this'll be a request in the future. Plus, it'll give us better google page ranking and crypto cred.

Since we're hosting the site on S3, it's gonna take Cloudfront and Route 53 to achieve what we want (kind of a headache).

Thoughts?

**Comment by palewire** [comment]
I've never successfully done this, so I'd need some help or to do some reading but I'm open to it. I think we are using Route 53 for some of our stuff now but my memory is failing me.

**Comment by rdmurphy** [comment]
@aboutaaron I'm mostly following, but just to be clear — how is the site currently deployed? Is everything static?

If it's all on S3, it's pretty straightforward. (For AWS, that is.) I'd be willing to help!

**Comment by palewire** [comment]
It is all static in three different buckets (blog, downloads site,
downloads file archive)

**Comment by palewire** [comment]
Links from @rdmurphy with some help:

http://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/SecureConnections.html#CNAMEsAndHTTPS

**Comment by palewire** [comment]
This is done.
