### ISSUE TITLE
Should we integrate with databricks?

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#159]
@anabranch [thinks so](https://twitter.com/bllchmbrs/status/776568608885387264)

**Comment by bllchmbrs** [comment]
What's the license on the data? I think it's super permissive right?

How much data is there? I remember it was on the order of GBs?

**Comment by palewire** [comment]
It is 100% public domain.

The full dump is about 750MB when zipped up.

**Comment by bllchmbrs** [comment]
Check it out:
https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/346304/3910054895802185/484361/latest.html

Is this just hosted on Amazon? The speed was actually quite fast when downloading, ~ 20 seconds. It'd be pretty easy for you to provide boilerplate code for people to use to set up all the tables and stuff like that. Then anyone can import that notebook and run it, then do their own analysis.

**Comment by palewire** [comment]
Yes, calaccess.download is a bucket on S3.
