### ISSUE TITLE
add a favicon to the site

### ISSUE THREAD

**Issue by underthecurve** [california-civic-data-coalition/django-calaccess-downloads-website#161]
A favicon for the site would look nice & be good for branding.

I made one of the bear using http://faviconit.com/ - see favicon.ico in the attached .zip file

[faviconit_bear.zip](https://github.com/california-civic-data-coalition/django-calaccess-downloads-website/files/475947/faviconit_bear.zip)

**Comment by palewire** [comment]
I think we've got the basic favicons in place. Well done!
