### ISSUE TITLE
Footer grid breaks at certain breakpoints

### ISSUE THREAD

**Issue by mhkeller** [california-civic-data-coalition/django-calaccess-downloads-website#163]
Possibly related to https://github.com/california-civic-data-coalition/django-calaccess-downloads-website/issues/156 but making a new issue because IIRC, a tablet landscape would be below `768px`.

Between `768px` and `992px` the footer grid displays as this this. It would look nicer if `Contact` were horizontally aligned with `About`. Seen in FF 48.0.1 and Chrome  53.0.2785.116 Mac
<img width="906" alt="screen shot 2016-09-16 at 1 47 49 pm" src="https://cloud.githubusercontent.com/assets/498744/18595933/e4c80d54-7c14-11e6-9cc5-a538bf6e4e9f.png">

I played around with removing a bunch of the styles but I can't get rid of it! It's infuriating. Tried setting `vertical-align: top;` and `display: inline-block;` to no avail. Will try to tinker with it later.

**Comment by palewire** [comment]
Interesting. Definitely a bug. We should be using vanilla bootstrap
gridding, which should work at all sizes. But it seems something is off
somewhere.

**Comment by s2tephen** [comment]
Needs to be fixed on the static (california-civic-data-coalition.github.io) pages as well. Just submitted a PR for it: https://github.com/california-civic-data-coalition/california-civic-data-coalition.github.io/pull/12
