### ISSUE TITLE
Dependency issues when installing chef

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-downloads-website#173]
The following error is happening during the step where we install chef as part of bootstrapping a new web server:
```
[ec2-54-68-94-132.us-west-2.compute.amazonaws.com] out: The following packages have unmet dependencies:
[ec2-54-68-94-132.us-west-2.compute.amazonaws.com] out:  git-core : Depends: git (> 1:1.7.0.2) but it is not going to be installed
[ec2-54-68-94-132.us-west-2.compute.amazonaws.com] out:  ruby2.0 : Depends: libruby2.0 (>= 2.0.0) but it is not going to be installed
[ec2-54-68-94-132.us-west-2.compute.amazonaws.com] out:            Depends: ruby (>= 1:1.9.3.1) but it is not installable
[ec2-54-68-94-132.us-west-2.compute.amazonaws.com] out:            Depends: rubygems-integration but it is not installable
[ec2-54-68-94-132.us-west-2.compute.amazonaws.com] out: E: Unable to correct problems, you have held broken packages.
```
If re-run `fab bootstrap`, there's no error. But maybe we can figure out what's going on with these dependencies?

**Comment by gordonje** [comment]
Git is also [listed in our dependencies](https://github.com/california-civic-data-coalition/django-calaccess-downloads-website/blob/master/chef/node.json.template#L10) to be installed later in the bootstrap. Seems to work fine if we don't do this up front.

That leaves ruby and it's dependencies...

**Comment by gordonje** [comment]
Also, Chef installs a recent version of ruby in `/opt/chef/embedded/`:
```sh
$ fab dev ssh
ubuntu@ip-172-31-19-182:~$ /opt/chef/embedded/bin/ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```
So unless we need ruby for anything else (besides running the chef client), we should be able to remove this from the `installchef` fab task as well.

**Comment by palewire** [comment]
![](https://media.giphy.com/media/3og0IMJcSI8p6hYQXS/giphy.gif)
