### ISSUE TITLE
Nail down a header link list

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#40]
- [ ] CAL-ACCESS [calaccess.californiacivicdata.org]
- [ ] Blog [www.californiacivicdata.org/posts/]
- [ ] About us [www.californiacivicdata.org/about/]

**Comment by sahilchinoy** [comment]
- [ ] CAL-ACCESS [calaccess.californiacivicdata.org]
- [ ] Version archive
- [ ] Docs [http://django-calaccess.californiacivicdata.org/en/latest/]
- [ ] Blog [www.californiacivicdata.org/posts/]
- [ ] About us [www.californiacivicdata.org/about/]

**Comment by gordonje** [comment]
- [ ] Raw Data (List)?
