### ISSUE TITLE
Would it be worth creating small graphics to tease out cool info?

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-downloads-website#48]
The data still seems fairly cryptic at this point and we need a "why you should care" call to action on the page. One idea would be to create some quick graphics similar to what we did/have on the campaign browser.

**Comment by palewire** [comment]
It might be something we could work into the detail and list pages in light ways, for sure.

**Comment by palewire** [comment]
Yes, but not before this launch.
