### ISSUE TITLE
Broad design for the site

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#5]
What does it look like? What is the basic UX navigation between pages? What is the lead art on the homepage? How does it connect to our other sites and repos?

**Comment by cwervo** [comment]
Any progress here? Would love to help draft/implement something for this.

**Comment by palewire** [comment]
@AndresCuervo It's something we're coming up on soon but haven't worked out. Right now we're working on the systems architecture to support the site, and we'll move to building the front end next. 

We've compiled a couple other data download sites we're interested in learning from. Have any thoughts on how what we can take away? Or what other sites we should be emulating?

http://www.fec.gov/finance/disclosure/ftp_download.shtml

https://www.illinoissunshine.org/

https://results.openaddresses.io/

http://openstates.org/downloads/
