### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#57]

**Comment by sahilchinoy** [comment]
Do we want anything else here?

**Comment by palewire** [comment]
I think we'll want to work in some teeny tiny links, as is typical on other sites.

**Comment by sahilchinoy** [comment]
So far
- CAL-ACCESS
- Version archive
- Raw data files

Do we want
- California Civic Data Coalition homepage
- Blog
- About

Anything else that should go here?

**Comment by aboutaaron** [comment]
See #66 for some of my ideas
