### ISSUE TITLE
Can the S3 copy for the latest URLs be abstracted into Django media backend system

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#71]
Right now we're doing custom boto work outside of Django that won't fly with out storage systems

**Comment by gordonje** [comment]
Seems like we just hook into Django's [File Storage](https://docs.djangoproject.com/en/1.9/topics/files/#file-storage)  interface.

``` python
from calaccess_raw.models.tracking import RawDataFile
from django.core.files.storage import default_storage
import os

raw_file = RawDataFile.objects.get(id=3612)

new_path = os.path.join('latest', os.path.basename raw_file.download_file_archive.name)

cp_file = default_storage.save(new_path, raw_file.download_file_archive)
```

The above code snippet takes an existing archived download file and saves a copy in the `latest/` directory of whatever default storage is currently configured for Django. I've successfully tried this from my local versions of the raw-data app (which is still just using the media root as the default storage backend) and the downloads-website (which is using S3 via the django-storages app).

With respect to whether we should do this inside the raw-data app's `updatecalaccessrawdata` command or somewhere in the downloads website: I'm feeling more strongly that this is outside the scope of what the raw-data app should be doing. If you were a user of the raw-data app, I think you would prefer to have explicit datetime-stamped directory names in your file system. And you wouldn't want an extra one named "latest". 

Our whole reason for doing this is to meet the needs of our website users, so I feel like that's where we should dealing with this concern.

Maybe the downloads website needs a separate "master" management command that (much like the update command) calls other management commands in the appropriate order:
1. `updatecalaccessrawdata`
2. `createlatestlinks`
3. `build`
4. `publish`

Under our current approach, these are all chained together in a single cron job. But if they are all in Django management command, we could handle exceptions more easily (e.g., if the update fails, how do we handle latest links?)

Am I at least in the ballpark here?

**Comment by palewire** [comment]
My one concern with switching to `default_storage.save(new_path, raw_file.download_file_archive)` is that it will trigger a reupload of the raw file that might run slower than the `copy_key` command in boto which seems to be pretty snappy somehow.

**Comment by palewire** [comment]
So since using boto directly is going to be faster I guess we're going to skip this.
