### ISSUE TITLE
Python3 testing and support

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#72]

**Comment by gordonje** [comment]
Fabric 1.x does not and will never support Python 3. 

Fabric 2 and the Invoke library it is built around are [still under development](http://www.fabfile.org/roadmap.html). So this will either have to wait, or we could consider switching to... I'm not sure what alternative. Just checked, and neither Ansible and SaltStack support Python 3 yet.

**Comment by palewire** [comment]
Not for now.
