### ISSUE TITLE
Version detail page punch list

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-downloads-website#80]
- [x] Broader headline without all the little date bits
- [x] Longer deckhead with all the date bits and maybe that old madlib idea
- [x] If/else or other trick to allow different format for latest page from date based
- [x] On latest page change archive link language to something like "Previous versions"
- [x] Try to sharpen up our section heds
- [x] Pull in only first line of docstrings for table descriptions so we can keep them punchy

**Comment by sahilchinoy** [comment]
Ideas for what to call a particular "version"
- Version
- Snapshot
- Release
- Archive
- Update

**Comment by sahilchinoy** [comment]
Does "Individual tables" make more sense than "Individual files," perhaps? And "Full release" instead of "Bulk data"?

**Comment by palewire** [comment]
This should now get our new breadcrumbs as well.

**Comment by palewire** [comment]
Things I see now:
- [ ] "Download unavailable" might be confusing language for files with zero records
- [x] It might be nice to have footnotes from the section description grafs down to the bottom that explain why some records and files are missing and links to our FAQs. It could also link to more precise record counts if we ever start charting those.
- [x] Breadcrumbs maybe a little too high above the headline. We should compare back against the mockup.
- [x] Do we need to more plainly explain what CAL-ACCESS is on these pages for newbies?

**Comment by palewire** [comment]
- [x] "Download unavailable" could be trimmed to download "unavailble".
- [x] Restore section bottom margins
