### ISSUE TITLE
Global site code/design punch list

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-downloads-website#88]
Some sitewide adjustments I think we should make. Feel free to offer feedback:
## Design
- [x] Make a heavier drop shadow on the header. It's kinda weak right now. I think we can go bigger
- [ ] Use actual fonts instead of weights for consistent rendering
- [x] change `wget` and `curl` to use custom white background and black type (don't like the default color for code blocks)
## Performance
- [ ] move all JavaScript to single file outside of templates. This'll aide when we need to handle page performance. Speaking of ...
- [ ] Minify CSS/JS
- [ ] vendor prefix any CSS3 usage, e.g., `box-shadow`

**Comment by aboutaaron** [comment]
I'll keep adding, but something to think about

**Comment by palewire** [comment]
I see a couple different things I'm going to break into separate tickets
