### ISSUE TITLE
Boxes need margin on mobile view.

### ISSUE THREAD

**Issue by ssdatar** [california-civic-data-coalition/django-calaccess-downloads-website#91]
The red boxes collapse into one giant box on mobile. They might need a margin, unless this was intentional. In which case, please close this issue :)

<img width="300" alt="screen shot 2016-08-15 at 10 30 56 pm" src="https://cloud.githubusercontent.com/assets/14825414/17686157/26c640ea-6338-11e6-9c29-f9ac06d57cdd.png">

**Comment by palewire** [comment]
Thanks for this. It's unclear if we're going to keep that feature in our final homepage design. But if we do we'll need to sort it out.

**Comment by palewire** [comment]
I think the switch to red on white we've made in the homepage branch settles this issue.
