### ISSUE TITLE
Same link for historical snapshot and documentation div (box #2 and #3)

### ISSUE THREAD

**Issue by ssdatar** [california-civic-data-coalition/django-calaccess-downloads-website#92]
Both divs link to `http://calaccess.californiacivicdata.org/files/`.

**Comment by palewire** [comment]
Thanks. If we ironed out the bugs, what do you think of the boxes as lead promo art on the page? Are they big and bold enough?

**Comment by ssdatar** [comment]
I think they stand out and would do well. But, in my opinion, a description of what CAL-ACCESS is should precede the boxes, just to complement what the boxes offer. Right now, the lead is `California Civic Data Coalition`, when the website is about `CAL-ACCESS`. What do you think?
